import { AgentSkill } from "../../harness/index.ts";

export const AdaptToStudentSkill = AgentSkill.make({
  name: "adapt-to-student",
  description: "Adapt quiz and test difficulty to the student's current knowledge state by checking their mastery profile before creating assessments.",
  content: [
    "# Adapt to Student",
    "",
    "Use this skill whenever you are about to create a quiz or test.",
    "",
    "## Step 1 - Check the student profile",
    "",
    'Always run `cli({ "input": "student profile" })` before creating a quiz or test.',
    "",
    "- If the profile has topics, note which are `learning` or `unknown` (weak) and which are `mastered` or `familiar` (strong).",
    "- If the profile is empty, proceed normally and tell the student their profile will build as they practice.",
    "",
    "## Step 2 - Adapt question difficulty",
    "",
    "When creating a quiz or test, follow these rules:",
    "",
    "- **Weight 60%+ of questions toward weak topics** (mastery = `learning` or `unknown` with attempts > 0).",
    "- **For `learning` topics**: write recall and comprehension questions (define, list, explain).",
    "- **For `familiar` topics**: write application questions (calculate, apply, compare).",
    "- **For `mastered` topics**: write analysis or synthesis questions (evaluate, design, critique).",
    "- If there are no weak topics, create a well-balanced quiz across all topics.",
    "",
    "## Step 3 - Label every question with a topicId",
    "",
    "Each question in the JSON must include a `topicId` field - a short snake_case identifier for the topic.",
    "Also include a human-readable label in the prompt or use the same value.",
    "",
    'Example question with topicId:',
    '```json',
    '{',
    '  "type": "multiple-choice",',
    '  "id": "q1",',
    '  "topicId": "photosynthesis",',
    '  "prompt": "What is the primary pigment used in photosynthesis?",',
    '  "options": [...],',
    '  "correctOptionId": "...",',
    '  "explanation": "..."',
    '}',
    '```',
    "",
    "## Step 4 - Record the attempt after grading",
    "",
    'After the student submits and the attempt is graded, run:',
    '`cli({ "input": "student record <attemptId>" })`',
    "",
    "This updates their mastery profile so future quizzes adapt further.",
    "",
    "## Fallback",
    "",
    "If `student profile` returns an error or the student asks to skip adaptation, create a balanced assessment and note that the profile will build over time."
  ].join("\n")
});
