import { AgentSkill } from "../../harness/index.ts";

export const FocusedQuizSkill = AgentSkill.make({
  name: "focused-quiz",
  description: "Generate a quiz where 100% of questions target the student's weak and mistake-prone topics.",
  content: [
    "# Focused Quiz",
    "",
    "Use this skill when the student asks for a focused quiz, targeted practice, or a quiz on their weak areas.",
    "",
    "## Step 1 — Get weak topics",
    "",
    'Run `cli({ "input": "student weak-topics" })` to retrieve topics with mastery `learning` or `unknown`.',
    "",
    "- If no weak topics exist, create a balanced quiz across all topics in the student\'s profile.",
    "- If the profile is empty, create a general quiz and note the profile will build with practice.",
    "",
    "## Step 2 — Retrieve recent mistakes",
    "",
    "For each weak topic, run:",
    '`cli({ "input": "student mistakes <topicId>" })`',
    "",
    "Use the mistake history to:",
    "- Understand which specific concepts the student gets wrong",
    "- Avoid repeating the exact same question wording",
    "- Target the underlying misconception, not just the surface question",
    "",
    "## Step 3 — Create the focused quiz",
    "",
    "All questions must be from weak topics (100% weighting). Rules:",
    "",
    "- **Every question must include `topicId`** (snake_case identifier matching the weak topic)",
    "- Do NOT reuse question prompts that appear in the mistake history — reframe the same concept differently",
    "- Write questions at the appropriate difficulty:",
    "  - `learning` topics: recall questions (define, identify, state)",
    "  - `unknown` topics with attempts: comprehension questions (explain, describe)",
    "- Aim for 5–8 questions total; weight more questions toward topics with the most mistakes",
    "",
    "Then call:",
    '`cli({ "input": "artifacts create \'{"kind":"quiz","title":"Focused Practice — <topics>","questions":[...]}\'" })`',
    "",
    "Use a concise title listing the main weak topics covered.",
    "",
    "## Step 4 — Prompt the student",
    "",
    "After creating the quiz, tell the student:",
    "- Which weak topics are covered",
    "- That this quiz is tailored to their recorded mistakes",
    "- That running `artifacts grade <attemptId>` after submission will update their mastery",
    "",
    "## Fallback",
    "",
    "If `student weak-topics` returns an error, fall back to a general quiz and note the profile was unavailable."
  ].join("\n")
});
