import { AgentSkill } from "../../harness/index.ts";

export const GenerateRevisionPlanSkill = AgentSkill.make({
  name: "generate-revision-plan",
  description: "Generate a focused revision note that explains the concepts behind the student's recorded mistakes, grouped by topic.",
  content: [
    "# Generate Revision Plan",
    "",
    "Use this skill whenever the student asks to review their mistakes, get a revision plan, or study what they got wrong.",
    "",
    "## Step 1 — Identify weak topics",
    "",
    'Run `cli({ "input": "student weak-topics" })` to get the topics where the student is struggling.',
    "",
    "- If there are no weak topics, tell the student they have no recorded weak areas and suggest taking a quiz instead.",
    "",
    "## Step 2 — Retrieve mistakes per topic",
    "",
    "For each weak topic, run:",
    '`cli({ "input": "student mistakes <topicId>" })`',
    "",
    "Collect the `questionPrompt`, `studentAnswer`, and `correctAnswer` fields for each mistake.",
    "",
    "## Step 3 — Write the revision note",
    "",
    "Create a note artifact that explains the weak concepts. Structure it as follows:",
    "",
    "- One `##` heading per weak topic",
    "- Under each heading, briefly explain the core concept",
    "- For each mistake: quote the question, explain why the student's answer was wrong, and clarify the correct answer",
    "- Use bullet points and bold for key terms",
    "- End each section with a one-sentence takeaway",
    "",
    "Then call:",
    '`cli({ "input": "artifacts create \'{"kind":"note","title":"Revision Plan — <date>","markdown":"..."}\'" })`',
    "",
    "Use today\'s date in the title (ISO format).",
    "",
    "## Step 4 — Confirm to the student",
    "",
    "After creating the note, tell the student:",
    '- Which topics are covered in the revision plan',
    '- How many mistakes were addressed',
    '- Suggest following up with `student focused-quiz` to test the revised concepts',
    "",
    "## Fallback",
    "",
    "If `student mistakes` returns no mistakes for any topic, tell the student their mistake history is empty and encourage them to complete and grade a quiz first."
  ].join("\n")
});
